CREATE TABLE RS_ROLES (
	ROLE_ID NUMBER(30) PRIMARY KEY,
	NAME VARCHAR2(10) NOT NULL UNIQUE
);

CREATE TABLE RS_EMPLOYEES (
	EMPLOYEE_ID NUMBER(30) PRIMARY KEY,
	USERNAME VARCHAR2(20) NOT NULL UNIQUE,
	ROLE_ID NUMBER(30) NOT NULL REFERENCES RS_ROLES (ROLE_ID),
	ENABLED NUMBER(1) NOT NULL
);

CREATE SEQUENCE RS_EMPLOYEES_SEQ START WITH 4;